name: Update badhosts

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython requests

      - name: Run update script
        env:
          FEED_URL: ${{ secrets.FEED_URL }}
        run: python src/proc.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add labor.db badhosts.txt
          git commit -m "Automated update of labor.db and badhosts.txt" || echo "No changes to commit"
          git push
